name: deploy_private
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - run: echo ${{ secrets.SUDO_PSW }} | sudo -S pm2 delete googlegenerative-ai-test
        continue-on-error: true
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Create .env file
        run: |
          touch .env
          echo NODE_ENV=production >> .env
          echo GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} >> .env
  start:
    needs: deploy
    runs-on: self-hosted
    steps:
      - run: echo ${{ secrets.SUDO_PSW }} | sudo -S pm2 start pm2.json
  test:
    needs: start
    runs-on: self-hosted
    steps:
      - run: npm run test --if-present